---
- hosts: 
  - "{{ pdc_hostname }}"
  - "{{ rdc_hostname }}"
  tasks:
  - name: Wait for system to become reachable over WinRM
    wait_for_connection:
      timeout: 900

  - name: Configure NLA Dependencies
    win_service:
      name: nlasvc
      start_mode: delayed
      dependencies: [ DNS, NTDS ]
      dependency_action: add

  - name: Restart NLA
    win_service:
      name: nlasvc
      state: restarted
      force_dependent_services: yes

  - name: Configure PDC DNS
    win_dns_client:
      adapter_names: '*'
      dns_servers:
      - "{{ rdc_hostname }}"
      - "{{ pdc_hostname }}"
      - 127.0.0.1
    when: inventory_hostname == pdc_hostname
  - name: Configure RDC DNS
    win_dns_client:
      adapter_names: '*'
      dns_servers:
      - "{{ pdc_hostname }}"
      - "{{ rdc_hostname }}"
      - 127.0.0.1
    when: inventory_hostname == rdc_hostname