---
- hosts: "{{ hostname }}"
  tasks:
  - name: Configure DNS
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses: 
      - "{{ dns_server | default(omit) }}"
    when: dns_server is defined
  - name: Set DNS Suffix
    win_shell: "Set-DnsClientGlobalSetting -SuffixSearchList @('{{ domain }}')"
    when: dns_server is defined
  - name: Join Domain
    win_domain_membership:
      dns_domain_name: "{{ domain }}"
      hostname: "{{ new_hostname }}"
      domain_admin_user: "{{ domain_admin }}"
      domain_admin_password: "{{ password }}"
      state: domain
    register: domain_state
  - name: Reboot
    win_reboot:
    when: domain_state.reboot_required