---
- name: Configure DC DNS Settings
  hosts: 
  - "{{ pdc_hostname }}"
  - "{{ rdc_hostname }}"
  tasks:
  - name: Configure PDC DNS
    win_dns_client:
      adapter_names: '*'
      dns_servers:
      - "{{ rdc_hostname }}"
      - "{{ pdc_hostname }}"
      - 127.0.0.1
    when: inventory_hostname == pdc_hostname
  - name: Configure RDC DNS
    win_dns_client:
      adapter_names: '*'
      dns_servers:
      - "{{ pdc_hostname }}"
      - "{{ rdc_hostname }}"
      - 127.0.0.1
    when: inventory_hostname == rdc_hostname